services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: nft_marketplace_db
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
    ports:
      - "5432:5432"
    networks:
      - nft_marketplace_network
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    depends_on: ["db"]
    build: 
      context: .
      target: prod
      dockerfile: Dockerfile
    environment: 
      DB_NAME: nft_marketplace_db
      DB_USERNAME: user1
      DB_PASSWORD: password1
      DB_HOST: db
      DB_PORT: 5432
      ENV: prod
    image: golang:1.23.2
    networks:
      - nft_marketplace_network
    ports:
      - "8080:8080"
    command: /app/build/server

networks:
  nft_marketplace_network:

volumes:
  db_data:

      
