services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: nft_marketplace_db
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
    ports:
      - "5432:5432"
    networks:
      - nft_marketplace_network
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    depends_on: ["db"]
    build: 
      context: . 
      dockerfile: Dockerfile
      target: dev
    environment: 
      DB_NAME: nft_marketplace_db
      DB_USERNAME: user1
      DB_PASSWORD: password1
      DB_HOST: db
      DB_PORT: 5432
      ENV: dev
      JWT_SECRET: 'fill me'
    image: golang:1.23.2
    networks:
      - nft_marketplace_network
    ports:
      - "8000:8000"
    volumes: 
      - .:/app
      - /go/pkg/mod
      - /go/bin

networks:
  nft_marketplace_network:

volumes:
  db_data:

      
